/* The credit list as it was hardcoded before the catalog moved to Firestore. It is used only to seed
   users/{uid}/credits the first time the new version runs (see migrateToCatalog in catalog.js).
   After that the app reads credits from Firestore; change them through the review queue, not here.
   activeFrom 2000-01-01 means "before tracking started", so every year's totals match the old app. */
export const SEED_CREDITS = [
  {"id":"csr-travel","card":"csr","name":"Travel credit","freq":"year","resetOn":"anniversary","amounts":[{"amount":300,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Applies automatically to almost any purchase that codes as travel.","info":["Resets on your card anniversary (May 1), not January 1.","No portal or activation needed. The statement credit posts a few days after the charge.","Counts for: airlines, hotels and motels, car rentals, cruise lines, travel agencies and booking sites, timeshares, campgrounds, trains, buses, taxis and rideshare (Uber, Lyft), limousines, ferries, public transit, tolls, and parking lots and garages.","Doesn’t count: airline gift cards, in-flight purchases, or merchants that sell travel inside another store."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":10},
  {"id":"csr-dd-r","card":"csr","name":"DoorDash restaurant promo","freq":"month","resetOn":"calendar","amounts":[{"amount":5,"from":"2000-01-01"},{"amount":15,"from":"2026-10-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"A promo in the DoorDash app for one restaurant order a month.","info":["Needs the complimentary DashPass membership that comes with the card. Activate it first.","Pay with Sapphire Reserve. The promo applies at checkout; it isn’t a statement credit.","It was $5 a month through September 2026 and is $15 from October.","Unused promos don’t roll over to the next month."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":20},
  {"id":"csr-dd-a","card":"csr","name":"DoorDash non-restaurant promo","freq":"month","resetOn":"calendar","amounts":[{"amount":10,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"A promo for a grocery, convenience or retail order on DoorDash.","info":["Not for restaurant orders. Use it on grocery, convenience, pharmacy or retail stores in DoorDash.","You get two of these $10 promos each month, one per order.","Needs DashPass activated and Sapphire Reserve as the payment method.","Doesn’t roll over."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":30},
  {"id":"csr-dd-b","card":"csr","name":"DoorDash non-restaurant promo, second","freq":"month","resetOn":"calendar","amounts":[{"amount":10,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"The second $10 non-restaurant DoorDash promo for the month.","info":["Same rules as the first: grocery, convenience or retail orders only, DashPass active, paid with Sapphire Reserve.","Each promo is for a separate order."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":40},
  {"id":"csr-lyft","card":"csr","name":"Lyft credit","freq":"month","resetOn":"calendar","amounts":[{"amount":10,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":"2027-09-30","valuation":"dollars","how":"$10 in Lyft credit each month through September 2027.","info":["Set Sapphire Reserve as your Lyft payment method.","The credit shows up in the Lyft app and is used on your next ride.","Rides also earn 5x points on the card.","Doesn’t roll over."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":50},
  {"id":"csr-peloton","card":"csr","name":"Peloton credit","freq":"month","resetOn":"calendar","amounts":[{"amount":10,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Up to $10 a month toward a Peloton membership.","info":["Only for a Peloton membership billed to Sapphire Reserve.","Equipment and apparel don’t count."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":60},
  {"id":"csr-tables","card":"csr","name":"Exclusive Tables dining","freq":"half","resetOn":"calendar","amounts":[{"amount":150,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Only at the select restaurants in Chase’s Sapphire Reserve Exclusive Tables list on OpenTable.","info":["Find the restaurants first: open the OpenTable app and look up the Sapphire Reserve Exclusive Tables list. Only those restaurants count.","Book through OpenTable and pay the bill with Sapphire Reserve.","$150 for January–June and $150 for July–December. Unused money doesn’t carry over."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":70},
  {"id":"csr-stubhub","card":"csr","name":"StubHub credit","freq":"half","resetOn":"calendar","amounts":[{"amount":150,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"For tickets bought on StubHub or viagogo.","info":["Activation required in your Chase account first.","$150 for January–June and $150 for July–December.","Pay with Sapphire Reserve."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":80},
  {"id":"csr-edit1","card":"csr","name":"The Edit hotel credit","freq":"year","resetOn":"calendar","amounts":[{"amount":250,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Only for hotels in The Edit collection, booked through Chase Travel.","info":["Must be booked through the Chase Travel portal. Booking the same hotel directly won’t trigger it.","Only hotels in The Edit collection qualify, and only on prepaid rates.","Stays need to be two nights or more.","Two $250 credits per calendar year. These bookings also earn 8x points."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":90},
  {"id":"csr-edit2","card":"csr","name":"The Edit hotel credit, second","freq":"year","resetOn":"calendar","amounts":[{"amount":250,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"The second $250 credit for The Edit this year.","info":["Same rules as the first: The Edit hotels, booked and prepaid through Chase Travel, two nights or more."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":100},
  {"id":"csr-select","card":"csr","name":"Select Hotels credit","freq":"year","resetOn":"calendar","amounts":[{"amount":250,"from":"2026-01-01"}],"activeFrom":"2026-01-01","activeTo":"2026-12-31","valuation":"dollars","how":"A 2026-only hotel credit, booked through Chase Travel.","info":["Must be booked through the Chase Travel portal.","Only participating hotel brands qualify. Check eligibility on the hotel listing in Chase Travel before you book.","Prepaid stays of two nights or more.","Ends December 31, 2026."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":110},
  {"id":"gold-uber","card":"gold","name":"Uber Cash","freq":"month","resetOn":"calendar","amounts":[{"amount":10,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"$10 lands in your Uber account on the 1st of each month.","info":["Add the Gold Card to your Uber account to receive it.","Works on U.S. rides or Uber Eats orders. Pick an Amex card at checkout.","Expires at the end of the month. It doesn’t roll over."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":120},
  {"id":"gold-dining","card":"gold","name":"Dining credit","freq":"month","resetOn":"calendar","amounts":[{"amount":10,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Only at Amex’s dining partners, not at any restaurant.","info":["Partners: Grubhub (including Seamless), The Cheesecake Factory, Buffalo Wild Wings, Wonder and Five Guys.","Amex changes this list from time to time. Goldbelly and Wine.com were dropped in 2026.","Enrollment required in the Amex app.","$10 a month, no rollover."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":130},
  {"id":"gold-dunkin","card":"gold","name":"Dunkin’ credit","freq":"month","resetOn":"calendar","amounts":[{"amount":7,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Up to $7 a month at U.S. Dunkin’ locations.","info":["Enrollment required in the Amex app.","Pay with the Gold Card. Loading a Dunkin’ gift card may not count.","No rollover."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":140},
  {"id":"gold-resy","card":"gold","name":"Resy credit","freq":"half","resetOn":"calendar","amounts":[{"amount":50,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Dine at a U.S. restaurant that’s on Resy and pay with the Gold Card.","info":["The restaurant has to be on Resy, but you don’t have to book through Resy.","Enrollment required.","$50 for January–June and $50 for July–December."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":150},
  {"id":"bilt-hotel","card":"bilt","name":"Bilt Travel hotel credit","freq":"half","resetOn":"calendar","amounts":[{"amount":200,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"dollars","how":"Book through the Bilt Travel portal. Any hotel listed there qualifies.","info":["Must be booked through the Bilt Travel portal in the Bilt app.","Any hotel on the portal works.","$200 for January–June and $200 for July–December, as statement credits."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":160},
  {"id":"bilt-cash","card":"bilt","name":"Bilt Cash","freq":"year","resetOn":"anniversary","amounts":[{"amount":200,"from":"2000-01-01"}],"activeFrom":"2000-01-01","activeTo":null,"valuation":"biltCash","how":"$200 of Bilt Cash on each account anniversary.","info":["Bilt Cash isn’t worth a dollar per dollar. $1 of Bilt Cash converts to 33.33 Bilt Points, which are worth about 33¢ to 66¢ depending on how you redeem them.","Some swaps are close to face value (for example, Grubhub credit), but most aren’t.","It’s also what unlocks your rent points: 1 point per rent dollar takes 3% of your rent in Bilt Cash.","Balances over $100 expire at the end of each calendar year.","The Value tab counts it at the rate you set on the Palladium card page."],"sourceUrl":null,"lastVerified":null,"changeNote":null,"sortOrder":170}
];
